### ISSUE TITLE
encoder stuck on uploading.

### ISSUE THREAD

**Issue by ermitchell78** [DanielnetoDotCom/YouPHPTube-Encoder#107]
I had this up and working a couple of weeks ago. Decided to start fresh and now cannot get the encoder to encode. I have read through the issues and tried all the options but nothing is working. File circle finishes but encoder sticks in downloading.
Enncoder log
24-Dec-2018 00:38:18 UTC] MP4 All
[24-Dec-2018 00:38:18 UTC] {"status":"error", "msg":"getDurationFromFile ERROR, File () Not Found"}
[24-Dec-2018 00:38:18 UTC] YouPHPTube-Encoder sending file to http://54.225.24.214/YouPHPTube/youPHPTubeEncoder.json
[24-Dec-2018 00:38:18 UTC] YouPHPTube-Encoder reading file from
[24-Dec-2018 00:38:18 UTC] YouPHPTube-Streamer answer {"error":false,"video_id":2}
[24-Dec-2018 00:38:18 UTC] {"error":false,"format":"mp4","file":"","resolution":"","videoDownloadedLink":null,"target":"http:\/\/54.225.2$
[24-Dec-2018 00:38:19 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function utf8_encode() in /var/www/html/YouPHPTube-Encoder$
Stack trace:
#0 /var/www/html/YouPHPTube-Encoder/objects/Encoder.php(241): Encoder::getVideoFile('http://52.207.1...', '3', '/var/www/html/Y...', '/va$
#1 /var/www/html/YouPHPTube-Encoder/objects/Encoder.php(456): Encoder::downloadFile('3')
#2 /var/www/html/YouPHPTube-Encoder/view/run.php(6): Encoder::run()
#3 {main}
  thrown in /var/www/html/YouPHPTube-Encoder/objects/Encoder.php on line 326
[24-Dec-2018 00:38:20 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function utf8_decode() in /var/www/html/YouPHPTube-Encoder$
Stack trace:
#0 /var/www/html/YouPHPTube-Encoder/objects/Encoder.php(794): url_get_contents('/var/www/html/Y...')
#1 /var/www/html/YouPHPTube-Encoder/view/status.php(34): Encoder::getVideoConversionStatus('3')
#2 {main}
  thrown in /var/www/html/YouPHPTube-Encoder/objects/functions.php on line 59
[24-Dec-2018 00:38:24 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function utf8_decode() in /var/www/html/YouPHPTube-Encoder$
Stack trace:
#0 /var/www/html/YouPHPTube-Encoder/objects/Encoder.php(794): url_get_contents('/var/www/html/Y...')
#1 /var/www/html/YouPHPTube-Encoder/view/status.php(34): Encoder::getVideoConversionStatus('3')
#2 {main}
  thrown in /var/www/html/YouPHPTube-Encoder/objects/functions.php on line 59
[24-Dec-2018 00:38:30 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function utf8_decode() in /var/www/html/YouPHPTube-Encoder$
Stack trace:
#0 /var/www/html/YouPHPTube-Encoder/objects/Encoder.php(794): url_get_contents('/var/www/html/Y...')
#1 /var/www/html/YouPHPTube-Encoder/view/status.php(34): Encoder::getVideoConversionStatus('3')
#2 {main}
  thrown in /var/www/html/YouPHPTube-Encoder/objects/functions.php on line 59

streamer log
[24-Dec-2018 00:38:18 UTC] Encoder receiving post
[24-Dec-2018 00:38:18 UTC] Do not need update duration: Video Object
(
    [id:Video:private] => 2
    [title:Video:private] => Test
    [clean_title:Video:private] => test
    [filename:Video:private] => _YPTuniqid_5c202a7aecf2c1.17711396
    [description:Video:private] =>
    [views_count:Video:private] =>
    [status:Video:private] => e
    [duration:Video:private] => EE:EE:EE
    [users_id:Video:private] => 1
    [categories_id:Video:private] => 1
    [old_categories_id:Video:private] =>
    [type:Video:private] => video
    [rotation:Video:private] => 0
    [zoom:Video:private] => 1
    [videoDownloadedLink:Video:private] =>
    [videoLink:Video:private] =>
    [next_videos_id:Video:private] => NULL
    [isSuggested:Video:private] => 0
    [videoGroups:Video:private] =>
    [trailer1:Video:private] =>
    [trailer2:Video:private] =>
    [trailer3:Video:private] =>
    [rate:Video:private] => 0
    [youtubeId:Video:private] =>
)

[24-Dec-2018 00:38:18 UTC] Files Received for video 2: Test

**Comment by DanielnetoDotCom** [comment]
This is the error

**PHP Fatal error: Uncaught Error: Call to undefined function utf8_encode()** 

fix it and you should be fine

**Comment by Bart274** [comment]
@DanielnetoDotCom and how should we solve this issue?

**Comment by DanielnetoDotCom** [comment]
@Bart274 if your error is the same above, you should easily find its solution on google.
