### ISSUE TITLE
Stuck at "Processing" on the page of encoder

### ISSUE THREAD

**Issue by VictorLi0213** [DanielnetoDotCom/YouPHPTube-Encoder#91]
I just installed the encoder. But when I try to log in to my encoder, I'm stuck as "processing". And I cannot go to my website either. But after I do "service apache2 restart", my website works again, but I still cannot log in to the encoder.
Here is my website: https://varomy.com
Encoder: https://varomy.com/encoder

Here are the logs:

[14-Sep-2018 20:42:18 UTC] Start Login Request
[14-Sep-2018 23:11:09 UTC] PHP Notice:  Undefined index: user in /var/www/html/objects/userRecoverPass.php on line 8
[14-Sep-2018 23:11:09 UTC] Start Login Request
[14-Sep-2018 23:48:29 UTC] PHP Notice:  Undefined index: captcha in /var/www/html/objects/sendEmail.json.php on line 9
[14-Sep-2018 23:49:59 UTC] Start Login Request
[15-Sep-2018 00:11:54 UTC] PHP Fatal error:  Uncaught Pecee\SimpleRouter\Exceptions\NotFoundHttpException: Route not found: "/index.php/2018/09/11/the-amazing-race-season-28-preview/" in /var/www/html/objects/simple-php-router/src/Pecee/SimpleRouter/Router.php:300
Stack trace:
#0 /var/www/html/objects/simple-php-router/src/Pecee/SimpleRouter/SimpleRouter.php(52): Pecee\SimpleRouter\Router->routeRequest()
#1 /var/www/html/index.php(132): Pecee\SimpleRouter\SimpleRouter::start()
#2 {main}
  thrown in /var/www/html/objects/simple-php-router/src/Pecee/SimpleRouter/Router.php on line 300
[15-Sep-2018 00:11:55 UTC] PHP Fatal error:  Uncaught Pecee\SimpleRouter\Exceptions\NotFoundHttpException: Route not found: "/index.php/2018/09/11/the-amazing-race-season-28-preview/" in /var/www/html/objects/simple-php-router/src/Pecee/SimpleRouter/Router.php:300
Stack trace:
#0 /var/www/html/objects/simple-php-router/src/Pecee/SimpleRouter/SimpleRouter.php(52): Pecee\SimpleRouter\Router->routeRequest()
#1 /var/www/html/index.php(132): Pecee\SimpleRouter\SimpleRouter::start()
#2 {main}
  thrown in /var/www/html/objects/simple-php-router/src/Pecee/SimpleRouter/Router.php on line 300
[15-Sep-2018 08:41:18 UTC] PHP Fatal error:  Uncaught Pecee\SimpleRouter\Exceptions\NotFoundHttpException: Route not found: "/index.php/2018/09/11/the-amazing-race-season-28-preview/" in /var/www/html/objects/simple-php-router/src/Pecee/SimpleRouter/Router.php:300
Stack trace:
#0 /var/www/html/objects/simple-php-router/src/Pecee/SimpleRouter/SimpleRouter.php(52): Pecee\SimpleRouter\Router->routeRequest()
#1 /var/www/html/index.php(132): Pecee\SimpleRouter\SimpleRouter::start()
#2 {main}
  thrown in /var/www/html/objects/simple-php-router/src/Pecee/SimpleRouter/Router.php on line 300
[15-Sep-2018 08:41:19 UTC] PHP Fatal error:  Uncaught Pecee\SimpleRouter\Exceptions\NotFoundHttpException: Route not found: "/index.php/2018/09/11/the-amazing-race-season-28-preview/" in /var/www/html/objects/simple-php-router/src/Pecee/SimpleRouter/Router.php:300
Stack trace:
#0 /var/www/html/objects/simple-php-router/src/Pecee/SimpleRouter/SimpleRouter.php(52): Pecee\SimpleRouter\Router->routeRequest()
#1 /var/www/html/index.php(132): Pecee\SimpleRouter\SimpleRouter::start()
#2 {main}
  thrown in /var/www/html/objects/simple-php-router/src/Pecee/SimpleRouter/Router.php on line 300
[15-Sep-2018 09:10:38 UTC] PHP Fatal error:  Uncaught Pecee\SimpleRouter\Exceptions\NotFoundHttpException: Route not found: "/index.php/category/fail/" in /var/www/html/objects/simple-php-router/src/Pecee/SimpleRouter/Router.php:300
Stack trace:
#0 /var/www/html/objects/simple-php-router/src/Pecee/SimpleRouter/SimpleRouter.php(52): Pecee\SimpleRouter\Router->routeRequest()
#1 /var/www/html/index.php(132): Pecee\SimpleRouter\SimpleRouter::start()
#2 {main}
  thrown in /var/www/html/objects/simple-php-router/src/Pecee/SimpleRouter/Router.php on line 300
[15-Sep-2018 11:02:32 UTC] PHP Fatal error:  Uncaught Pecee\SimpleRouter\Exceptions\NotFoundHttpException: Route not found: "/index.php/actor-listing/" in /var/www/html/objects/simple-php-router/src/Pecee/SimpleRouter/Router.php:300
Stack trace:
#0 /var/www/html/objects/simple-php-router/src/Pecee/SimpleRouter/SimpleRouter.php(52): Pecee\SimpleRouter\Router->routeRequest()
#1 /var/www/html/index.php(132): Pecee\SimpleRouter\SimpleRouter::start()
#2 {main}
  thrown in /var/www/html/objects/simple-php-router/src/Pecee/SimpleRouter/Router.php on line 300
[15-Sep-2018 11:02:32 UTC] PHP Fatal error:  Uncaught Pecee\SimpleRouter\Exceptions\NotFoundHttpException: Route not found: "/index.php/actor-listing/" in /var/www/html/objects/simple-php-router/src/Pecee/SimpleRouter/Router.php:300
Stack trace:
#0 /var/www/html/objects/simple-php-router/src/Pecee/SimpleRouter/SimpleRouter.php(52): Pecee\SimpleRouter\Router->routeRequest()
#1 /var/www/html/index.php(132): Pecee\SimpleRouter\SimpleRouter::start()
#2 {main}
  thrown in /var/www/html/objects/simple-php-router/src/Pecee/SimpleRouter/Router.php on line 300
[15-Sep-2018 14:09:28 UTC] PHP Fatal error:  Uncaught Pecee\SimpleRouter\Exceptions\NotFoundHttpException: Route not found: "/index.php/2018/09/11/americas-test-kitchen-season-16-trailer/" in /var/www/html/objects/simple-php-router/src/Pecee/SimpleRouter/Router.php:300
Stack trace:
#0 /var/www/html/objects/simple-php-router/src/Pecee/SimpleRouter/SimpleRouter.php(52): Pecee\SimpleRouter\Router->routeRequest()
#1 /var/www/html/index.php(132): Pecee\SimpleRouter\SimpleRouter::start()
#2 {main}
  thrown in /var/www/html/objects/simple-php-router/src/Pecee/SimpleRouter/Router.php on line 300
[15-Sep-2018 14:09:29 UTC] PHP Fatal error:  Uncaught Pecee\SimpleRouter\Exceptions\NotFoundHttpException: Route not found: "/index.php/2018/09/11/americas-test-kitchen-season-16-trailer/" in /var/www/html/objects/simple-php-router/src/Pecee/SimpleRouter/Router.php:300
Stack trace:
#0 /var/www/html/objects/simple-php-router/src/Pecee/SimpleRouter/SimpleRouter.php(52): Pecee\SimpleRouter\Router->routeRequest()
#1 /var/www/html/index.php(132): Pecee\SimpleRouter\SimpleRouter::start()
#2 {main}
  thrown in /var/www/html/objects/simple-php-router/src/Pecee/SimpleRouter/Router.php on line 300
[15-Sep-2018 14:10:56 UTC] PHP Fatal error:  Uncaught Pecee\SimpleRouter\Exceptions\NotFoundHttpException: Route not found: "/index.php/tag/movie/" in /var/www/html/objects/simple-php-router/src/Pecee/SimpleRouter/Router.php:300
Stack trace:
#0 /var/www/html/objects/simple-php-router/src/Pecee/SimpleRouter/SimpleRouter.php(52): Pecee\SimpleRouter\Router->routeRequest()
#1 /var/www/html/index.php(132): Pecee\SimpleRouter\SimpleRouter::start()
#2 {main}
  thrown in /var/www/html/objects/simple-php-router/src/Pecee/SimpleRouter/Router.php on line 300
[15-Sep-2018 16:58:34 UTC] Start Login Request
[15-Sep-2018 18:45:10 UTC] PHP Fatal error:  Uncaught Pecee\SimpleRouter\Exceptions\NotFoundHttpException: Route not found: "/index.php/tag/news/" in /var/www/html/objects/simple-php-router/src/Pecee/SimpleRouter/Router.php:300
Stack trace:
#0 /var/www/html/objects/simple-php-router/src/Pecee/SimpleRouter/SimpleRouter.php(52): Pecee\SimpleRouter\Router->routeRequest()
#1 /var/www/html/index.php(132): Pecee\SimpleRouter\SimpleRouter::start()
#2 {main}
  thrown in /var/www/html/objects/simple-php-router/src/Pecee/SimpleRouter/Router.php on line 300
[15-Sep-2018 18:45:11 UTC] PHP Fatal error:  Uncaught Pecee\SimpleRouter\Exceptions\NotFoundHttpException: Route not found: "/index.php/tag/news/" in /var/www/html/objects/simple-php-router/src/Pecee/SimpleRouter/Router.php:300
Stack trace:
#0 /var/www/html/objects/simple-php-router/src/Pecee/SimpleRouter/SimpleRouter.php(52): Pecee\SimpleRouter\Router->routeRequest()
#1 /var/www/html/index.php(132): Pecee\SimpleRouter\SimpleRouter::start()
#2 {main}
  thrown in /var/www/html/objects/simple-php-router/src/Pecee/SimpleRouter/Router.php on line 300
[15-Sep-2018 18:47:35 UTC] PHP Fatal error:  Uncaught Pecee\SimpleRouter\Exceptions\NotFoundHttpException: Route not found: "/index.php/category/others/" in /var/www/html/objects/simple-php-router/src/Pecee/SimpleRouter/Router.php:300
Stack trace:
#0 /var/www/html/objects/simple-php-router/src/Pecee/SimpleRouter/SimpleRouter.php(52): Pecee\SimpleRouter\Router->routeRequest()
#1 /var/www/html/index.php(132): Pecee\SimpleRouter\SimpleRouter::start()
#2 {main}
  thrown in /var/www/html/objects/simple-php-router/src/Pecee/SimpleRouter/Router.php on line 300
[15-Sep-2018 20:50:20 UTC] Start Login Request
[15-Sep-2018 20:56:34 UTC] Start Login Request
[15-Sep-2018 20:56:50 UTC] Start Login Request
[15-Sep-2018 20:58:24 UTC] Start Login Request
[15-Sep-2018 20:58:28 UTC] Start Login Request
[15-Sep-2018 20:58:32 UTC] Start Login Request
[15-Sep-2018 21:00:28 UTC] Show Ads Count started
[15-Sep-2018 21:00:28 UTC] Show Ads Count 1
[15-Sep-2018 21:00:28 UTC] Show Ads Count 1
[15-Sep-2018 21:00:28 UTC] VMAP select those options: Array
(
    [0] => 2
    [1] => 3
)

[15-Sep-2018 21:00:28 UTC] VMAP select those options: Array
(
    [0] => 2
    [1] => 3
)

[15-Sep-2018 21:02:19 UTC] Start Login Request

**Comment by DanielnetoDotCom** [comment]
Please read this https://github.com/DanielnetoDotCom/YouPHPTube/wiki/Admin-manual

**Comment by VictorLi0213** [comment]
Hi, but now I got this problem when I go to the encoder:
<img width="960" alt="2018-09-16 10 33 54" src="https://user-images.githubusercontent.com/29973121/45598121-287b3500-b99c-11e8-9538-03af373dffb6.png">

**Comment by VictorLi0213** [comment]
And sometimes it also says that the user or password is not correct.
Here is the log:
https://varomy.com/encoder/videos/youphptube.log

**Comment by VictorLi0213** [comment]
Oh I have just solved it. Thanks!

**Comment by DanielnetoDotCom** [comment]
what is your domain?

**Comment by VictorLi0213** [comment]
I just solved the problem and it's working fine right now.
Thanks!

**Comment by DanielnetoDotCom** [comment]
Great
