### ISSUE TITLE
Encoder Erro Upload

### ISSUE THREAD

**Issue by DinhoUnisul** [DanielnetoDotCom/YouPHPTube-Encoder#93]
Ola criei o meu próprio encoder porem quando termino de fazer upload da um erro.
https://imgur.com/a/Gm36Bax
https://imgur.com/a/Gm36Bax

**Comment by DanielnetoDotCom** [comment]
não vejo erro nenhum, olhe o arquivo de log.

https://github.com/DanielnetoDotCom/YouPHPTube/wiki/How-to-find-errors-on-YouPHPTube

**Comment by DanielForthman** [comment]
Having the same issue. Fresh Ubuntu 18.04 install and fresh clone from github:

tail -n 200 -f /var/www/html/encoder/videos/youphptube.log

[25-Nov-2018 00:08:03 UTC] MP4 All
[25-Nov-2018 00:08:03 UTC] {"status":"error", "msg":"getDurationFromFile ERROR, File () Not Found"}
[25-Nov-2018 00:08:03 UTC] YouPHPTube-Encoder sending file to https://www.ratstick.com/youPHPTubeEncoder.json
[25-Nov-2018 00:08:03 UTC] YouPHPTube-Encoder reading file from
[25-Nov-2018 00:08:03 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function curl_init() in /var/www/html/encoder/objects/Encoder.php:696
Stack trace:
#0 /var/www/html/encoder/view/upload.php(74): Encoder::sendFile('', 0, 'mp4', Object(Encoder))
#1 {main}
  thrown in /var/www/html/encoder/objects/Encoder.php on line 696

**Comment by DanielForthman** [comment]
When adding a video from youtube:

[25-Nov-2018 00:27:40 UTC] MP4 HD
[25-Nov-2018 00:27:40 UTC] {"status":"error", "msg":"getDurationFromFile ERROR, File () Not Found"}
[25-Nov-2018 00:27:42 UTC] YouPHPTube-Encoder sending file to https://www.ratstick.com/youPHPTubeEncoder.json
[25-Nov-2018 00:27:42 UTC] YouPHPTube-Encoder reading file from
[25-Nov-2018 00:27:42 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function curl_init() in /var/www/html/encoder/objects/Encoder.php:696
Stack trace:
#0 /var/www/html/encoder/view/youtubeDl.json.php(69): Encoder::sendFile('', 0, 'mp4', Object(Encoder))
#1 /var/www/html/encoder/view/youtubeDl.json.php(115): addVideo('https://www.you...', '2')
#2 {main}
  thrown in /var/www/html/encoder/objects/Encoder.php on line 696

**Comment by DanielnetoDotCom** [comment]
Hi

Google for the fatal error " PHP Fatal error: Uncaught Error: Call to undefined function curl_init()"

After fix it you will be fine

**Comment by dfreddie** [comment]
Hello,
I have the same error after ubuntu upgrade.

"msg":"getDurationFromFile ERROR, File () Not Found"}
PHP Fatal error:  Uncaught Error: Call to undefined function curl_init() in /var/www/html/encoder/objects/Encoder.php:759

server: Ubuntu 18.04.2 LTS
php -v: PHP 7.2.15-0ubuntu0.18.04.1 (cli) (built: Feb  8 2019 14:54:22) ( NTS )
            Copyright (c) 1997-2018 The PHP Group
            Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
             with Zend OPcache v7.2.15-0ubuntu0.18.04.1, Copyright (c) 1999-2018, by Zend Technologies

php -i | grep ini
Configuration File (php.ini) Path => /etc/php/7.2/cli
Loaded Configuration File => /etc/php/7.2/cli/php.ini
Scan this dir for additional .ini files => /etc/php/7.2/cli/conf.d
Additional .ini files parsed => /etc/php/7.2/cli/conf.d/10-mysqlnd.ini,
/etc/php/7.2/cli/conf.d/10-opcache.ini,
/etc/php/7.2/cli/conf.d/10-pdo.ini,
/etc/php/7.2/cli/conf.d/15-xml.ini,
/etc/php/7.2/cli/conf.d/20-bz2.ini,
/etc/php/7.2/cli/conf.d/20-calendar.ini,
/etc/php/7.2/cli/conf.d/20-ctype.ini,
**/etc/php/7.2/cli/conf.d/20-curl.ini,**
/etc/php/7.2/cli/conf.d/20-dom.ini,
/etc/php/7.2/cli/conf.d/20-exif.ini,
/etc/php/7.2/cli/conf.d/20-fileinfo.ini,
/etc/php/7.2/cli/conf.d/20-ftp.ini,
/etc/php/7.2/cli/conf.d/20-gd.ini,
/etc/php/7.2/cli/conf.d/20-gettext.ini,
/etc/php/7.2/cli/conf.d/20-iconv.ini,
/etc/php/7.2/cli/conf.d/20-json.ini,
/etc/php/7.2/cli/conf.d/20-mbstring.ini,
/etc/php/7.2/cli/conf.d/20-mysqli.ini,
/etc/php/7.2/cli/conf.d/20-pdo_mysql.ini,
/etc/php/7.2/cli/conf.d/20-phar.ini,
/etc/php/7.2/cli/conf.d/20-php-remctl.ini,
/etc/php/7.2/cli/conf.d/20-posix.ini,
/etc/php/7.2/cli/conf.d/20-propro.ini,
/etc/php/7.2/cli/conf.d/20-raphf.ini,
/etc/php/7.2/cli/conf.d/20-readline.ini,
/etc/php/7.2/cli/conf.d/20-shmop.ini,
/etc/php/7.2/cli/conf.d/20-simplexml.ini,
/etc/php/7.2/cli/conf.d/20-sockets.ini,
/etc/php/7.2/cli/conf.d/20-sysvmsg.ini,
/etc/php/7.2/cli/conf.d/20-sysvsem.ini,
/etc/php/7.2/cli/conf.d/20-sysvshm.ini,
/etc/php/7.2/cli/conf.d/20-tokenizer.ini,
/etc/php/7.2/cli/conf.d/20-wddx.ini,
/etc/php/7.2/cli/conf.d/20-xmlreader.ini,
/etc/php/7.2/cli/conf.d/20-xmlwriter.ini,
/etc/php/7.2/cli/conf.d/20-xsl.ini,
/etc/php/7.2/cli/conf.d/20-zip.ini
user_ini.cache_ttl => 300 => 300
user_ini.filename => .user.ini => .user.ini
init_command_executed_count => 0
init_command_failed_count => 0
com_init_db => 0
Classes => AppendIterator, ArrayIterator, ArrayObject, BadFunctionCallException, BadMethodCallException, CachingIterator, CallbackFilterIterator, DirectoryIterator, DomainException, EmptyIterator, FilesystemIterator, FilterIterator, GlobIterator, InfiniteIterator, InvalidArgumentException, IteratorIterator, LengthException, LimitIterator, LogicException, MultipleIterator, NoRewindIterator, OutOfBoundsException, OutOfRangeException, OverflowException, ParentIterator, RangeException, RecursiveArrayIterator, RecursiveCachingIterator, RecursiveCallbackFilterIterator, RecursiveDirectoryIterator, RecursiveFilterIterator, RecursiveIteratorIterator, RecursiveRegexIterator, RecursiveTreeIterator, RegexIterator, RuntimeException, SplDoublyLinkedList, SplFileInfo, SplFileObject, SplFixedArray, SplHeap, SplMinHeap, SplMaxHeap, SplObjectStorage, SplPriorityQueue, SplQueue, SplStack, SplTempFileObject, UnderflowException, UnexpectedValueException

**Comment by DanielnetoDotCom** [comment]
@dfreddie Make sure you are using PHP 7.2 on your server, you may have multiple PHP versions on it.

**Comment by dfreddie** [comment]
Thanks. U had right! Php7.0 was installed on system. After removing it all good!
